server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${SPRING_DATASOURCE_USERNAME:account_user}
    password: ${SPRING_DATASOURCE_PASSWORD:account_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: true

customer-service:
  url: ${CUSTOMER_SERVICE_URL:http://localhost:8081}
card-service:
  url: ${CARD_SERVICE_URL:http://localhost:8083}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}